baseURL: https://billthefarmer.github.io/questionnaire/
languageCode: en-gb
title: Questionnaire
theme: simple
publishDir: d:/billthefarmer.github.io/questionnaire/
metaDataFormat: yaml
params:
  copyright: Copyright 2018 Bill Farmer
markup:
  goldmark:
    renderer:
      unsafe: true
